### ISSUE TITLE
helpDesk class

### ISSUE THREAD

**Issue by ghost** [alitquan/Ruff-Banditz_Mallick-A_Naing-N#1]
when you finish the main method of APQ, make helpDesk class and basically copy the main method

**Comment by alitquan** [comment]
dw bro... I did the whole project by myself.... and I hope mr.brown can see through your fake number of committs.,,, smh im taking the day off........... how could you do this bro... unfriended on facebook.. smh, just uploading a keyboard class that we already had for hw..... wth
